### ISSUE TITLE
Pressing the Download button nothing happens

### ISSUE THREAD

**Issue by MasothU** [mediathekview/MediathekViewMobile#1]
**Describe the bug**
Pressing the Download button, nothing happens. No popup which quality to download and no download appears in the download section 

**To Reproduce**
1. Select any media you want 
2. Click on 'Download' 

**Expected behavior**
Either a popup which asks which quality to download or any download progress visible in download section

**Operation System (please complete the following information):**
 - OS: Android 
- Version of the OS: 9

**Device(please complete the following information):**
 - Device: Samsung Galaxy S8

**Additional context**
I really like your Web version and use that often. 
I hope you can fix the issue. An android version would be great. 
Another setting where downloads should be saved to would be useful too

**Comment by danielfoehrKn** [comment]
Thanks for your input! 

Can you please try again with the latest Release version 1.0? For a couple hours, the version was outdated. I did not think that anybody would be that quick :)

**Expected behavior at the moment:**

- Ask for filesystem permission (if not granted yet)
- download video showing status on the tile itself as well as in the "Bibliothek section"

**Download Directory**
 At the moment, all the downloads are being saved to the external SD Card into the MediathekView Folder. I am thinking about making this configurable if some people request it. 
However, if you do not want to export the files, you can conveniently use the in app video player that has some more features (e.g pick up at the playback position where you left).

**Multiple Qualities**
Same thing here. Currently downloads default quality that I found to be very good quality and sufficient for tablets and smartphones alike.
This one I ll make configurable for sure, just need some more time and wanted to gather some feedback, so thanks again!


In any case, if you still encounter that issue, can you please let me know and (if possible) send me the logcat output of the app?

**Comment by MasothU** [comment]
Any news? Would be too bad if there is no app for android.
I still have issues with the download. 
Try to download one of the larger quarks releases (44mins)
When I try it throws an error. 
Small releases like Wissen vor acht for example do work
![Screenshot_20200214-173333](https://user-images.githubusercontent.com/17427639/74549914-c176fc80-4f50-11ea-9fce-54b2fa986819.jpg)

**Comment by cemrich** [comment]
In the meantime you may want to give Zapp a try: https://f-droid.org/de/packages/de.christinecoenen.code.zapp/

**Comment by MasothU** [comment]
Oh, I totally missed that zapp is now part of the mediathekview family and even more didn't know that you can now download episodes with it. Great thing and thanks for the hint! 😊

**Comment by danielfoehrKn** [comment]
Closing this for now. You can expect an update fixing the mentioned issues.
